[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.79"
js-sys = "0.3.56"
sha1 = "0.10.1"
hex = "0.4.3"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'
